/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'djain' at '5/24/17 1:54 PM' with Gradle 2.14.1
 *
 * @author djain, @date 5/24/17 1:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
